### ISSUE TITLE
Add more memory

### ISSUE THREAD

**Issue by 50bvd** [hoshizaki-iori/minecraft-docker#1]
hi, how i modify jvm args for add more ram to my mcsrv container?

**Comment by 50bvd** [comment]
its okay i edit the docker-compose.yml and add MEMORY: "4G" and docker-compose up -d

**Comment by h0shizaki** [comment]
That right. You can add more configuration in docker-compose.yml.
I have added the reference docs of the docker image and some tutorial vdo in README.
hope it useful for everyone 😁.
